spring:
  application:
    name: backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatapp}
  config:
    import: optional:classpath:application-secrets.yml
  main:
    allow-circular-references: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSelectKeyForJWTTokenGenerationEnsureItIsLongEnough}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.web.socket: INFO

file:
  upload-dir: uploads

